-- return {
--   -- snippets
--   {
--     "L3MON4D3/LuaSnip",
--     dependencies = {
--       "rafamadriz/friendly-snippets",
--       config = function()
--         require("luasnip.loaders.from_vscode").lazy_load()
--       end,
--     },
--     opts = {
--       history = true,
--       delete_check_events = "TextChanged",
--     },
--     -- stylua: ignore
--     keys = {
--       -- {
--       --   "<tab>",
--       --   function()
--       --     return require("luasnip").jumpable(1) and "<Plug>luasnip-jump-next" or "<tab>"
--       --   end,
--       --   expr = true, silent = true, mode = "i",
--       -- },
--       { "<Down", function() require("luasnip").jump(1) end, mode = "s" },
--       { "<Up>", function() require("luasnip").jump(-1) end, mode = { "i", "s" } },
--     },
--   },

--   -- auto completion

--   {
--     "hrsh7th/nvim-cmp",
--     version = false, -- last release is way too old
--     event = "InsertEnter",
--     dependencies = {
--       "hrsh7th/cmp-nvim-lsp",
--       "hrsh7th/cmp-buffer",
--       "hrsh7th/cmp-path",
--       "saadparwaiz1/cmp_luasnip",
--       "tzachar/cmp-tabnine",
--     },
--     opts = function()
--       local cmp = require("cmp")
--       return {
--         completion = {
--           completeopt = "menu,menuone,noinsert",
--         },
--         snippet = {
--           expand = function(args)
--             require("luasnip").lsp_expand(args.body)
--           end,
--         },
--         mapping = cmp.mapping.preset.insert({
--           ["<C-b>"] = cmp.mapping.scroll_docs(-4),
--           ["<C-f>"] = cmp.mapping.scroll_docs(4),
--           ["<C-e>"] = cmp.mapping.abort(),
--           ["<tab>"] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
--         }),
--         sources = cmp.config.sources({
--           { name = "cmp_tabnine" },
--           { name = "nvim_lsp" },
--           { name = "luasnip" },
--           { name = "buffer" },
--           { name = "path" },
--         }),
--         formatting = {
--           format = function(_, item)
--             local icons = require("lazyvim.config").icons.kinds
--             if icons[item.kind] then
--               item.kind = icons[item.kind] .. item.kind
--             end
--             return item
--           end,
--         },
--         experimental = {
--           ghost_text = {
--             hl_group = "LspCodeLens",
--           },
--         },
--       }
--     end,
--   },

--   {
--     "tzachar/cmp-tabnine",
--     build = "./install.sh",
--     dependencies = "hrsh7th/nvim-cmp",
--   },
-- }
