-- return {
--   {
--     "akinsho/toggleterm.nvim",
--     version = "*",
--     opts = {
--       setup = {
--         shade_terminals = false,
--         highlights = {
--           StatusLine = { guifg = "#ffffff", guibg = "#0E1018" },
--           StatusLineNC = { guifg = "#ffffff", guibg = "#0E1018" },
--         },
--       },
--     },
--   },
-- }
